#  Declaration Of Arrays In NumPy

In [ ]:
import numpy as np

a = np.array([23,56,43,89,12]) # Simple 1D array declaration in the numpy
print("Array a is :", a)

Array a is : [23 56 43 89 12]


In [ ]:
import numpy as np
# Diff Between Lists & Arrays 
list = [1,2,3,4,5]
print(f"The multiplication using lists will print this : {list*2}") # This will print the list two times

array = np.array([1,2,3,4,5])
print(f"The multiplication using arrays will print this : {array*2}") # This will multiply each element by 2

The multiplication using lists will print this : [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
The multiplication using arrays will print this : [ 2  4  6  8 10]


# Creating Arrays With Default Values

In [ ]:
import numpy as np

# Array Of Zeros 
a1 = np.zeros(4) # 1D array 
a2 = np.zeros((3,3)) # 2D array
print(a1)
print(a2)

# Array Of Ones
b1 = np.ones(3) # 1D array
b2 = np.ones((5,6))
print(b1)
print(b2)

# Array Of full
c2 = np.full((3,4),7) # 2D array it wil print the given fixed values 
print(c2)

# Array Of random values
d1 = np.random.random(5)
d2 = np.random.random((3,4))
print(d1)
print(d2)

# Array Of range
e1 = np.arange(0,10,1) # (start , stop , step)
print(e1)

# Array Of linspace
f1 = np.linspace(0,10,5) # (start , stop , number of values)
print(f1)

# Array Of eye
g1 = np.eye(4) # Identity matrix of size 4x4    
print(g1)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[0.42419326 0.9461499  0.23099703 0.79693947 0.90713856]
[[0.03079265 0.55070843 0.67887667 0.75904925]
 [0.469772   0.70884751 0.74683065 0.77008765]
 [0.7749069  0.90485823 0.78219829 0.66942184]]
[0 1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Properties 

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]]) # original array
print("Original array:", arr) 

print(arr.ndim)  # number of dimensions

print(arr.shape)  # shape of the array

print(arr.size)  # total number of elements

print(arr.dtype)  # data type of the elements

print(arr.itemsize)  # size of each element in bytes

print(arr.nbytes)  # total size of the array in bytes

print(arr.T)  # transpose of the array

print(arr.flatten())  # flatten the array to 1D

print(arr.reshape(3, 2))  # reshape the array to 3x2

print(arr.sum())  # sum of all elements

print(arr.min())  # minimum element

print(arr.max())  # maximum element

print(arr.mean())  # mean of the elements

print(arr.std())  # standard deviation of the elements

print(arr.var())  # variance of the elements 

print(np.unique(arr))  # unique elements in the array

Original array: [[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
8
48
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
21
1
6
3.5
1.707825127659933
2.9166666666666665
