In [1]:
import numpy as np

#  Declaration Of Arrays In NumPy

In [ ]:
a = np.array([23,56,43,89,12]) # Simple 1D array declaration in the numpy
print("Array a is :", a)

Array a is : [23 56 43 89 12]


In [ ]:
# Diff Between Lists & Arrays 
list = [1,2,3,4,5]
print(f"The multiplication using lists will print this : {list*2}") # This will print the list two times

array = np.array([1,2,3,4,5])
print(f"The multiplication using arrays will print this : {array*2}") # This will multiply each element by 2

The multiplication using lists will print this : [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
The multiplication using arrays will print this : [ 2  4  6  8 10]


# Creating Arrays With Default Values

In [2]:

# Array Of Zeros 
a1 = np.zeros(4) # 1D array 
a2 = np.zeros((3,3)) # 2D array
print(a1)
print(a2)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# Array Of Ones
b1 = np.ones(3) # 1D array
b2 = np.ones((5,6))
print(b1)
print(b2)

[1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [4]:
# Array Of full
c2 = np.full((3,4),7) # 2D array it wil print the given fixed values 
print(c2)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [5]:
# Array Of random values
d1 = np.random.random(5)
d2 = np.random.random((3,4))
print(d1)
print(d2)

[0.89943299 0.39469114 0.27687704 0.00429283 0.32054777]
[[0.24580231 0.90542758 0.87311871 0.4584952 ]
 [0.45575487 0.80673688 0.28942571 0.22263341]
 [0.82796051 0.35853793 0.58922505 0.41985394]]


In [6]:
# Array Of range
e1 = np.arange(0,10,1) # (start , stop , step)
print(e1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# Array Of linspace
f1 = np.linspace(0,10,5) # (start , stop , number of values)
print(f1)

[ 0.   2.5  5.   7.5 10. ]


In [8]:
# Array Of eye
g1 = np.eye(4) # Identity matrix of size 4x4    
print(g1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Properties 

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # original array
print("Original array:", arr) 

print(arr.ndim)  # number of dimensions

print(arr.shape)  # shape of the array

print(arr.size)  # total number of elements

print(arr.dtype)  # data type of the elements

print(arr.itemsize)  # size of each element in bytes

print(arr.nbytes)  # total size of the array in bytes

print(arr.T)  # transpose of the array

print(arr.flatten())  # flatten the array to 1D

print(arr.reshape(3, 2))  # reshape the array to 3x2

print(arr.sum())  # sum of all elements

print(arr.min())  # minimum element

print(arr.max())  # maximum element

print(arr.mean())  # mean of the elements

print(arr.std())  # standard deviation of the elements

print(arr.var())  # variance of the elements 

print(arr.argmax())  # index of the maximum element

print(arr.argmin())  # index of the minimum element

print(np.unique(arr))  # unique elements in  array


Original array: [[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
8
48
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
21
1
6
3.5
1.707825127659933
2.9166666666666665
5
0
[1 2 3 4 5 6]
