#  Declaration Of Arrays In NumPy

In [1]:
import numpy as np

a = np.array([23,56,43,89,12]) # Simple 1D array declaration in the numpy
print("Array a is :", a)

Array a is : [23 56 43 89 12]


In [2]:
# Diff Between Lists & Arrays 
list = [1,2,3,4,5]
print(f"The multiplication using lists will print this : {list*2}") # This will print the list two times

array = np.array([1,2,3,4,5])
print(f"The multiplication using arrays will print this : {array*2}") # This will multiply each element by 2

The multiplication using lists will print this : [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
The multiplication using arrays will print this : [ 2  4  6  8 10]


# Creating Arrays With Default Values

In [ ]:
import numpy as np

# Array Of Zeros 
a1 = np.zeros(4) # 1D array 
a2 = np.zeros((3,3)) # 2D array
print(a1)
print(a2)

# Array Of Ones
b1 = np.ones(3) # 1D array
b2 = np.ones((5,6))
print(b1)
print(b2)

# Array Of full
c1 = np.full(6)
c2 = np.full((3,4))
print(c1)
print(c2)


[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
