In [1]:
import numpy as np

# Array Slicings

In [ ]:
# 2D Array Slicings
arr_2d = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])

print("\nOriginal 2D array:\n", arr_2d) 
print("Slicing rows 1 to 3 and columns 2 to 4:\n", arr_2d[1:4, 2:5]) 
print("Slicing all rows and columns 1 to 3:\n", arr_2d[:, 1:4])
print("Slicing rows 2 to end and all columns:\n", arr_2d[2:, :])
print("Slicing first 3 rows and first 2 columns:\n", arr_2d[:3, :2])
print("Slicing with step of 2 for rows and columns:\n", arr_2d[::2, ::2])
print("Reversing rows and columns:\n", arr_2d[::-1, ::-1])
print("Slicing last 2 rows and last 3 columns:\n", arr_2d[-2:, -3:])


Original 2D array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Slicing rows 1 to 3 and columns 2 to 4:
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]
Slicing all rows and columns 1 to 3:
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]
Slicing rows 2 to end and all columns:
 [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Slicing first 3 rows and first 2 columns:
 [[ 1  2]
 [ 6  7]
 [11 12]]
Slicing with step of 2 for rows and columns:
 [[ 1  3  5]
 [11 13 15]
 [21 23 25]]
Reversing rows and columns:
 [[25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
Slicing last 2 rows and last 3 columns:
 [[18 19 20]
 [23 24 25]]


# Array Sorting 

In [ ]:
# 1D Sorting
arr = np.array([64, 34, 25, 12, 22, 11, 90])
sorted_arr = np.sort(arr) # original array remains unchanged it creates a new sorted array
print(sorted_arr) # Output: [11 12 22 25 34 64 90]

In [7]:
arr = np.array([64, 34, 25, 12, 22, 11, 90])
arr.sort() # sorts the array in place
print(arr) # Output: [11 12 22 25 34 64 90]

[11 12 22 25 34 64 90]


In [6]:
arr = np.array([64, 34, 25, 12, 22, 11, 90])
arr.sort()
desc_sorted_arr = arr[::-1]
print(desc_sorted_arr) # Output: [90 64 34 25 22 12 11]

[90 64 34 25 22 12 11]


In [8]:
arr = np.array([64, 34, 25, 12, 22, 11, 90])
idx = np.argsort(arr)
print(idx) # Output: [0 1 2 3 4 5 6]    
print(arr[idx]) # Output: [11 12 22 25 34 64 90]

[5 3 4 2 1 0 6]
[11 12 22 25 34 64 90]


In [9]:
# 2D Sorting
arr_2d = np.array([[64, 34, 25],
                   [12, 22, 11],
                   [90, 45, 67]])


In [10]:

sorted_arr_2d_axis0 = np.sort(arr_2d, axis=0) # sort along columns
print(sorted_arr_2d_axis0)

[[12 22 11]
 [64 34 25]
 [90 45 67]]


In [11]:

sorted_arr_2d_axis1 = np.sort(arr_2d, axis=1) # sort along rows
print(sorted_arr_2d_axis1)

[[25 34 64]
 [11 12 22]
 [45 67 90]]


In [12]:

arr_2d.sort(axis=1) # sorts each row in place
print(arr_2d)       

[[25 34 64]
 [11 12 22]
 [45 67 90]]


In [13]:
sorted_desc_axis0 = arr_2d[::-1, ::-1] # descending sort along columns
print(sorted_desc_axis0)

[[90 67 45]
 [22 12 11]
 [64 34 25]]


# Array Filtering

In [14]:
# 1D Filtering
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [15]:
filtered_arr = arr[arr > 25]
print("Filtered array (elements > 25):", filtered_arr) 

Filtered array (elements > 25): [30 35 40 45 50]


In [16]:
mask = (arr > 25) & (arr < 45)
print(mask) 
filtered_arr_mask = arr[mask]
print("Filtered array with mask (25 < elements < 45):", filtered_arr_mask)

[False False False False  True  True  True False False]
Filtered array with mask (25 < elements < 45): [30 35 40]


In [17]:
# 2D Filtering
arr_2d = np.array([[10, 15, 20],
                   [25, 30, 35],
                   [40, 45, 50],
                   [55, 60, 65]])

In [18]:
filtered_arr_2d = arr_2d[arr_2d > 30]
print("Filtered 2D array (elements > 30):", filtered_arr_2d) 

Filtered 2D array (elements > 30): [35 40 45 50 55 60 65]


In [19]:
mask = (arr_2d >= 20) & (arr_2d <= 50)
print(mask) 

[[False False  True]
 [ True  True  True]
 [ True  True  True]
 [False False False]]


In [20]:

filtered_arr_2d_mask = arr_2d[mask] 
print("Filtered 2D array with mask (20 <= elements <= 50):", filtered_arr_2d_mask) 

Filtered 2D array with mask (20 <= elements <= 50): [20 25 30 35 40 45 50]


In [21]:
rows = arr_2d[np.any(arr_2d > 50, axis=1)]
print("Rows with any element > 50:\n", rows) 

Rows with any element > 50:
 [[55 60 65]]


In [22]:
cols = arr_2d[:, np.all(arr_2d > 20, axis=0)]
print("Columns with all elements > 20:\n", cols) 

Columns with all elements > 20:
 []
