# Fancy Indexing

In [5]:
import numpy as np

 # 1D indexing example
array_1d = np.array([10, 20, 30, 40, 50])
new_arr = array_1d[3]  # Accessing elements at indices 3, 2, and 5
print("1D Array:", new_arr)
# 2D indexing example
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:", array_2d[0:2, 1:3])  # Accessing a sub-array from rows 0-1 and columns 1-2

# 3D indexing example
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("3D Array:", array_3d[1:3, 0:2, 0:2])  # Accessing a sub-array from depth 1-2, rows 0-1, and columns 0-1


1D Array: 40
2D Array: [[2 3]
 [5 6]]
3D Array: [[[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# np.where()

In [7]:
# It is If-else for arrays
# syntax: np.where(condition,value if true,value if false)

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr>25 , 1 , 0 ) # if arr>25 then 1 else 0
print("If-Else Array:", result)

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.where([arr2 > 5])
print("Indices where condition is met:", indices)

If-Else Array: [0 0 1 1 1]
Indices where condition is met: (array([0, 0, 0, 0]), array([1, 2, 2, 2]), array([2, 0, 1, 2]))


# Add & Remove Elements 

In [8]:
# using np.append()
import numpy as np 

# 1D array append
arr1 = np.array([1, 2, 3])
new_arr1 = np.append(arr1, [4, 5, 6]) # syntax: np.append(original_array, values_to_append)
print("Appended 1D Array:", new_arr1)

# 2D array append
arr2 = np.array([[1, 2], [3, 4]])
new_arr2 = np.append(arr2, [[5, 6]], axis=0)  # Append as a new row , axis = 1 for column
print("Appended 2D Array:\n", new_arr2)


Appended 1D Array: [1 2 3 4 5 6]
Appended 2D Array:
 [[1 2]
 [3 4]
 [5 6]]


In [9]:
# usingnp.insert()
import numpy as np

# 1D array insert
arr1 = np.array([10, 20, 30, 40, 50])
new_arr1 = np.insert(arr1, 2, 25)  # Syntax: np.insert(original_array, index, value_to_insert)
print("Array after insertion in 1D:", new_arr1)

# 2D array insert
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
new_arr2 = np.insert(arr2, 1, [7, 8, 9], axis=0)  # Insert as a new row at index 1
print("Array after insertion in 2D:\n", new_arr2)

Array after insertion in 1D: [10 20 25 30 40 50]
Array after insertion in 2D:
 [[1 2 3]
 [7 8 9]
 [4 5 6]]
