# Advance Operations With Bussiness Examples 

In [ ]:
import numpy as np

In [ ]:
# Data Structure : [Company_Id , 2021 , 2022 , 2023 , 2024 , 2025 ]

sales_data = np.array([
    [101, 150000, 175000, 200000, 225000, 250000], # Google
    [102, 120000, 130000, 140000, 150000, 160000], # Amazon
    [103, 300000, 320000, 340000, 365555, 385555], # Microsoft
    [104, 500000, 600000, 700000, 800000, 900000], # Apple
    [105, 225555, 245555, 265555, 285555, 311111]  # Facebook
])   

print("=== Sales Data ===")

print("sales data shape is : ", sales_data.shape)

print("sample data for 1st 3 company : ", sales_data[: , 1:])

=== Sales Data ===
sales data shape is :  (5, 6)
sample data for 1st 3 company :  [[150000 175000 200000 225000 250000]
 [120000 130000 140000 150000 160000]
 [300000 320000 340000 365555 385555]
 [500000 600000 700000 800000 900000]
 [225555 245555 265555 285555 311111]]


In [9]:
# Total sales per year 

print(np.sum(sales_data , axis = 0))
year_total = np.sum(sales_data[: , 1:], axis = 0)

[    515 1295555 1470555 1645555 1826110 2006666]
